base_url = "https://www.cs.cornell.edu/courses/cs6120/2019fa"
compile_sass = true
highlight_code = false
build_search_index = false
generate_rss = true

title = "CS 6120"

[extra]
favicon = "/img/favicon.ico"
bigicon = "/img/favicon152.png"

[[extra.links]]
name = "Slack"
url = "https://cs6120-2019fa.slack.com/"

[[extra.links]]
name = "GitHub"
url = "https://github.com/sampsyo/cs6120"
